# Generated by Django 4.2.23 on 2025-06-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='record',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Emergency', 'Emergency'), ('Follow-up', 'Follow-up'), ('Specialist', 'Specialist')], default='General', max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Follow-up Required', 'Follow-up Required')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
