# Generated by Django 4.2.23 on 2025-06-20 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_message'),
    ]

    operations = [
    ]
